Fixed custom fields in issue
mindbox-cloud/Mindbox.YandexTracker pull request #12
Opened 2024-10-22 17:59 UTC by toporoviv

2024-10-22 18:30 UTC, Markeli requested changes

2024-10-22 18:30 UTC, Markeli commented on Mindbox.YandexTracker.Abstractions/Entities/Issue.cs
> +		// JsonSerializer.Deserialize не может определиться с перегрузкой, т.к. значение словаря CustomFields - object, поэтому
Так мы решили, что словарик у нас хранит json, а не object. А в методах GetCustonField/SetCustonField мы выполняет конвертацию из/в json.

2024-10-22 18:30 UTC, Markeli commented on Mindbox.YandexTracker.Abstractions/Entities/Issue.cs
> +		if (CustomFields[customFieldId] is string jsonString)
1. Нет проверки входных аргументов. Надо надобавить.
2. Нет проверки, что в словаре есть что-то с таким ключиком. Из-за это в runtime может быть неприятное исключение. Вообще если поле null, то трекер даже не вернет это поле в ответ на запрос. Но пользователь может запросить поле все равно. Так что надо улучшить проверки. И если ничего в словаре нет, возвращать default.

2024-10-28 16:23 UTC, Markeli requested changes

2024-10-28 16:23 UTC, Markeli commented on Mindbox.YandexTracker.Abstractions/Entities/Issue.cs
> +	internal Dictionary<string, object> CustomFields { get; init; } = [];
А зачем тут object, если у нас там только string хранится?

2024-10-28 16:23 UTC, Markeli commented on Mindbox.YandexTracker.Abstractions/Entities/Issue.cs
> +		ArgumentNullException.ThrowIfNull(value);
Но мы же можем поставить пустое значение в поле. Тогда эту проверка не нужна.

2024-10-28 16:26 UTC, toporoviv commented on Mindbox.YandexTracker.Abstractions/Entities/Issue.cs
> +	internal Dictionary<string, object> CustomFields { get; init; } = [];
в лс договорились переделать словарик так, чтобы он хранил сериализованные объекты. Обрезали доступ к словарю, сделав его internal, чтобы клиент случайно не добавил свой кастомный объект, который порушит всю эту логику. Теперь доступ к словарю осуществляется через два метода - GetCustomField (получение поля по ключу + десериализация) и SetCustomField - установка значение для данного ключа с сериализацией

2024-10-28 16:29 UTC, toporoviv commented on Mindbox.YandexTracker.Abstractions/Entities/Issue.cs
> +	internal Dictionary<string, object> CustomFields { get; init; } = [];
если поставить здесь string, то в реквестах и респонсах придется возиться с JToken. Не знаю как лучше поступить: переписывать все это дело под JToken или оставить через object (разница по сути незаметна)

2024-10-28 16:42 UTC, Markeli commented on Mindbox.YandexTracker.Abstractions/Entities/Issue.cs
> +	internal Dictionary<string, object> CustomFields { get; init; } = [];
Гавено, ща подумаю.

2024-10-28 17:16 UTC, Markeli commented on Mindbox.YandexTracker.Abstractions/Entities/Issue.cs
> +	internal Dictionary<string, object> CustomFields { get; init; } = [];
Не придумал, давай оставим как есть.

2024-10-28 17:19 UTC, Markeli commented on Mindbox.YandexTracker.Abstractions/Entities/Issue.cs
> +		var json = JsonSerializer.Serialize(value);
Оставь и тут, и словаря CustomFields пояснение, почему мы так сделали. Выглядит как костыль, пусть хоть коммент подскажет, почему мы его оставили.

2024-10-31 08:22 UTC, gizdatullin reviewed
Не сильно всматривался, чисто накидал, что в глаза бросилось.

2024-10-31 08:22 UTC, gizdatullin commented on Mindbox.YandexTracker/Dtos/Responses/Read/GetIssueResponse.cs
>  	public bool IsFavorite { get; init; }
favorite или IsFavorite?

2024-10-31 08:22 UTC, gizdatullin commented on Mindbox.YandexTracker/Extensions/JsonElementExtensions.cs
> +			Display = element.GetProperty("display").GetString() ?? string.Empty,
Точно проставлять пустую строку - это хорошая идея?

2024-10-31 09:23 UTC, Markeli approved these changes

2024-10-31 09:23 UTC, merged

2024-10-31 09:24 UTC, Markeli commented
Упс, сори, погорячился с вливанием.

2024-10-31 09:28 UTC, toporoviv commented on Mindbox.YandexTracker.Abstractions/Entities/UserDetailedInfo.cs
> +	public required long Id { get; init; }
да, тут все норм

2024-10-31 09:29 UTC, toporoviv commented on Mindbox.YandexTracker/Dtos/Responses/Read/GetIssueResponse.cs
>  	public bool IsFavorite { get; init; }
да, тут нужно исправить на Favorite

2024-10-31 10:00 UTC, gizdatullin commented on Mindbox.YandexTracker.Abstractions/Entities/Project.cs
> +	public Collection<string>? IssueQueueKeys { get; init; }
Давай все равно его инициализировать пустым массивом. Правилом хорошего тона является всегда возвращать пустую коллекцию вместо null.