Improvements
mindbox-cloud/Mindbox.YandexTracker pull request #18
Opened 2024-11-05 10:10 UTC by gizdatullin

https://tracker.yandex.ru/GITLAB-78

2024-11-05 10:47 UTC, gizdatullin commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> -		return result.ToQueueLocalField() with { FieldName = queueLocalField.FieldName };
Надо в сеттинги добавить локаль.

2024-11-05 10:47 UTC, gizdatullin commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +			return [];
Это прям грустно.

2024-11-05 10:51 UTC, gizdatullin commented on Mindbox.YandexTracker.Abstractions/Dtos/Requests/Create/CreateIssueRequest.cs
> +public sealed record CreateIssueRequest : CustomFieldsRequest
Во всех респонсах issue еще остались некоторые поля, которые я не добавил. Но это слишком муторно. Предлагаю либо не в этом pr (и так большой), либо по мере надобности.

2024-11-06 07:14 UTC, gizdatullin commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +			return [];
Это неправда. Все работает как часики без этого.

2024-11-06 07:15 UTC, gizdatullin commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> -		return result.ToQueueLocalField() with { FieldName = queueLocalField.FieldName };
Сделал себе пометку, сделаю в следующем pr.

2024-11-06 11:51 UTC, Markeli commented on Mindbox.YandexTracker.Abstractions/Dtos/CustomFieldDtos.cs
> +	public Dictionary<string, JsonElement> Fields { get; init; } = [];
У нас есть методы `GetCustomFields`/`SetCustomFields` с десереализацей.

Больше пользы делать публичным `Fields` нет. Давай его сделаем internal, чтобы потребителей либы он не смущал.

2024-11-06 11:57 UTC, Markeli commented on Mindbox.YandexTracker.Abstractions/Dtos/Requests/Create/CreateProjectRequest.cs
> +	public string? Author { get; init; }
Тут и в других местах ты убрал Id у части полей. У Яндекса в API есть некая неоднородность:
- то тебе в качестве условного Lead прислали UserInfo
- то тебе прислали ИД

Хотелось в нашей либе от этого избавиться, чтобы по контрактам было понятно, что тут именно ИД. В чем профит убрать суффикс Id? Максимально соответствовать API трекера?

2024-11-06 11:58 UTC, Markeli commented on Mindbox.YandexTracker.Abstractions/Dtos/Responses/Create/CreateCommentResponse.cs
> +	public Collection<UserShortInfoDto> Summonees { get; init; } = [];
Кстати назойливые Collection решил не убирать?

2024-11-06 11:59 UTC, gizdatullin commented on Mindbox.YandexTracker.Abstractions/Dtos/Requests/Create/CreateProjectRequest.cs
> +	public string? Author { get; init; }
Да, это осноновная мотивация.
Плюс видел как в pr Ильи было избавление от полей, где contract name совпадает с именем поля.

2024-11-06 11:59 UTC, gizdatullin commented on Mindbox.YandexTracker.Abstractions/Dtos/Responses/Create/CreateCommentResponse.cs
> +	public Collection<UserShortInfoDto> Summonees { get; init; } = [];
Не хотел pr еще и этим раздувать.

2024-11-06 15:03 UTC, Markeli requested changes

2024-11-06 15:03 UTC, Markeli commented on Mindbox.YandexTracker.Template/ServiceCollectionExtensions.cs
> +		return services
Считаешь, что встроенный декоратор для кэширования не нужен?

Да, мы вроде делаем универсальную либу. Но для себя, в первую очередь. И кэширование частых запросов типа статуса, резолюций и т.д. - не плохая вещь.

Ту она была opt in.

2024-11-06 15:07 UTC, gizdatullin commented on Mindbox.YandexTracker.Abstractions/Dtos/CustomFieldsHelper.cs
> +		throw new KeyNotFoundException($"Key '{customFieldId}' not found in custom fields.");
Валидно. Переделаю на TryGet с экстешненом под текущее поведение.

2024-11-07 11:40 UTC, Markeli commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
>  	public async Task GetIssueAsync_IssueKey_ResponseIsNotNullAndIssueSuccessfullyCreated()
Давай сейчас в пайплайн включу прогон тестов.

2024-11-07 11:41 UTC, gizdatullin commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
>  	public async Task GetIssueAsync_IssueKey_ResponseIsNotNullAndIssueSuccessfullyCreated()
Там по плану был еще один pr, в котом бы включил тесты.

2024-11-07 11:41 UTC, gizdatullin commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
>  	public async Task GetIssueAsync_IssueKey_ResponseIsNotNullAndIssueSuccessfullyCreated()
Но я не разобрался, откуда секреты брать и отложил этот вопрос, пока тут не смрежу.

2024-11-07 11:42 UTC, gizdatullin commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
>  	public async Task GetIssueAsync_IssueKey_ResponseIsNotNullAndIssueSuccessfullyCreated()
Инициализация коллекций все сломала.

2024-11-07 11:46 UTC, gizdatullin commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
>  	public async Task GetIssueAsync_IssueKey_ResponseIsNotNullAndIssueSuccessfullyCreated()
Там с полями косяк, чиню.

2024-11-07 12:03 UTC, Markeli approved these changes

2024-11-07 12:08 UTC, merged