Improvements v2
mindbox-cloud/Mindbox.YandexTracker pull request #20
Opened 2024-11-07 12:13 UTC by gizdatullin

https://tracker.yandex.ru/GITLAB-78

2024-11-07 12:42 UTC, Markeli requested changes

2024-11-07 12:42 UTC, Markeli commented on .github/workflows/pull-request.yml
> +        run: dotnet restore
Лишние пробелы тут?)

2024-11-07 12:42 UTC, Markeli commented on Mindbox.YandexTracker.Abstractions/CustomFieldsHelper.cs
> +	public static bool TryGetCustomField<T>(
Может, extension метод по красоте сделать?

2024-11-07 12:42 UTC, Markeli commented on Mindbox.YandexTracker.Abstractions/Dtos/PaginationSettings.cs
> +	public int? MaxPageRequestCount { get; set; }
Можно оставить коммент: Если не задано, будут запрошены все доступные данные.

2024-11-07 12:42 UTC, Markeli commented on Mindbox.YandexTracker.Abstractions/IYandexTrackerClient.cs
> +		PaginationSettings? paginationSettings = null,
По красоте было бы оставить у методов док-комментарий для этого параметра: Если не задано, то будут использоваться параметры пагинации по умолчанию (из конфига).

2024-11-07 12:42 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClientOptions.cs
> +	public string? LanguageTag { get; set; }
Default нам сюда не нужно задавать?

2024-11-07 12:42 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +	private static readonly PaginationSettings _defaultPaginationSettings = new();
Можно сделать их публично доступными и ссылаться на них в доке. Будет максимально прозрачно.

2024-11-07 12:42 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		parameters["perPage"] = pagination.PerPage.ToString(CultureInfo.InvariantCulture);
Решение с пагинацией - элегантное. Ставлю лайк!

2024-11-07 12:42 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> -		static async Task CheckRateLimitExceededAsync(
Мы выпилили retry из коробки, Polly из коробки тоже не предлагаем. Мб, хотя бы в ReadMe привести пример, как для трекера лучше настроить политику? Типа 429 - ретраим, остальное нет.

2024-11-08 10:03 UTC, gizdatullin commented on Mindbox.YandexTracker/YandexTrackerClientOptions.cs
> +	public string? LanguageTag { get; set; }
Нет, запросы и без этого проходят. По умолчанию, как я понимаю, используется значение ru.

2024-11-08 10:11 UTC, gizdatullin commented on Mindbox.YandexTracker.Abstractions/IYandexTrackerClient.cs
> +		PaginationSettings? paginationSettings = null,
Там все равно немного некрасиво получается.
- Там компилятор начинает жаловаться на то, что для остальных параметров нет доки. Не хочется супресить это.
- Это по сути деталь реализации, так что сделать красивые референсы на код, откуда настройки подтягиюватся не получится.

Решил пока так оставить.

2024-11-08 11:16 UTC, Markeli approved these changes

2024-11-08 11:16 UTC, Markeli commented on .github/workflows/publish-dev.yaml
> +      - name: Pack
Тесты не хочешь сюда включить?
Всяко полезнее об ошибке будет узнать раньше.

2024-11-08 11:16 UTC, Markeli commented on Mindbox.YandexTracker.Tests/example.appsettings.secret.json
> +  "__HowToUse": "Rename this file to appsettings.secret.json and fill the fields. Integration test will use it.",
Тут лайк!

2024-11-08 11:16 UTC, Markeli commented on README.md
> +                    .HandleResult(response => (int)response.StatusCode >= 500)
И добавь, плиз, сюда 429 код для примера.

2024-11-08 11:24 UTC, gizdatullin commented on .github/workflows/publish-dev.yaml
> +      - name: Pack
Я специально убрал. Если хочется тесты гонять, лучше pr из ветки сделать. Там сразу два пайплайна запустятся.

2024-11-08 13:38 UTC, merged