Added implementation
mindbox-cloud/Mindbox.YandexTracker pull request #3
Opened 2024-10-02 11:56 UTC by toporoviv

[Написать библиотеку для работы с Яндекс.Трекером](https://tracker.yandex.ru/GITLAB-5)

2024-10-02 14:59 UTC, Markeli requested changes

2024-10-02 14:59 UTC, Markeli commented on Directory.Build.props
> +    <VersionMajor>1</VersionMajor>
У нас пока не production ready либа, не надо ставить 1 как можорную. Лучше повышай минорную версию.

2024-10-02 14:59 UTC, Markeli commented on Mindbox.YandexTracker.Abstractions/Dtos/Responses/Read/GetAttachmentResponse.cs
> +	public required string Size { get; init; }
Тут точно строка? Выглядит как-то странно.

2024-10-02 14:59 UTC, Markeli commented on Mindbox.YandexTracker/Exceptions/NoRetryException.cs
> +public class NoRetryException : YandexTrackerException
Лучше обзови `YandexTrackerRetryLimitExceededException`.

2024-10-02 14:59 UTC, Markeli commented on Mindbox.YandexTracker/Extensions/DtoExtension.cs
> +	public static Resolution ToResolution(this FieldInfo value) => value.Id switch
Этот и похожие ниже методы направильные, писал об этом в одном из прошлых PR.

Типы резолюцию, типы задач, статусы - это изменяемые штуки. Можно в Трекере зайти в определенный раздел, удалить существующие значения, изменить их или добавить новые. Так что такой мапинг неправильный.

Надо запрашивать эти значения с API.

2024-10-02 14:59 UTC, Markeli commented on Mindbox.YandexTracker/Extensions/DtoExtension.cs
> +		"firstSupportLine" => new IssueStatus
Какое-то неконсистентное форматирование: в одном месте все в одну строку, чуть ниже - с новой строки все.

Приведи, плиз, к единообразию.

2024-10-02 14:59 UTC, Markeli commented on Mindbox.YandexTracker/Extensions/DtoExtension.cs
> +public static class DtoExtension
Лучше сделать internal, чтобы наружу не торчал класс.

2024-10-02 14:59 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClientOptions.cs
> +public sealed record YandexTrackerClientOptions
Отступа не хватает(

2024-10-02 14:59 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +namespace Mindbox.YandexTracker;
Где отступы, Лебовски?)

2024-10-02 14:59 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +public sealed class YandexTrackerClient(
Общее замечание по классу. В методах из интерфейса у тебя есть токен отмены. Но в самой логике ты его не используешь. Это неправильно. Надо пофиксить.

2024-10-02 14:59 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		if (expand is not null and not QueueExpandData.None)
Почти в каждом методе этот кусок кода повторяется (отдельно для `QueueExpandData`, отдельно для `IssuesExpandData`). Можно спокойно вынести в общие методы и переиспользовать, код будет чище.

2024-10-02 14:59 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +			Thread.Sleep(retryPeriod);
Ой, нет, так делать не надо. С тредами работать - моветон в 2024. Нужен delay - `await Task.Delay(retryPeriod, cancellationToken);`

2024-10-02 14:59 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		while (true)
Перепишу лучше на do-while и проверку результата в конце сделай. Так лучше, потому что условие выхода из цикла в одном ожидаемом месте. Код так чище получается.

2024-10-02 15:02 UTC, toporoviv commented on Mindbox.YandexTracker/Exceptions/NoRetryException.cs
> +public class NoRetryException : YandexTrackerException
поправил

2024-10-02 15:04 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +namespace Mindbox.YandexTracker;
поправил

2024-10-02 15:12 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +			Thread.Sleep(retryPeriod);
поправил

2024-10-02 15:14 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClientOptions.cs
> +public sealed record YandexTrackerClientOptions
поправил

2024-10-02 15:15 UTC, toporoviv commented on Mindbox.YandexTracker/Extensions/DtoExtension.cs
> +public static class DtoExtension
поправил

2024-10-02 15:24 UTC, toporoviv commented on Mindbox.YandexTracker/Extensions/DtoExtension.cs
> +		"firstSupportLine" => new IssueStatus
поправил

2024-10-02 15:24 UTC, toporoviv commented on Mindbox.YandexTracker.Abstractions/Dtos/Responses/Read/GetAttachmentResponse.cs
> +	public required string Size { get; init; }
да, судя по [api](https://yandex.cloud/ru/docs/tracker/concepts/issues/get-attachments-list)

2024-10-02 15:26 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +public sealed class YandexTrackerClient(
поправил

2024-10-03 09:03 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +public sealed class YandexTrackerClient(
Стянул изменения, но фикса не увидел. Ты еще не залил исправления?

2024-10-03 09:03 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +			Thread.Sleep(retryPeriod);
Тут тоже фикса нет.

2024-10-03 10:02 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +public sealed class YandexTrackerClient(
еще не заливал) я для себя написал

2024-10-03 10:15 UTC, toporoviv commented on Directory.Build.props
> +    <VersionMajor>1</VersionMajor>
поправил

2024-10-03 10:15 UTC, toporoviv commented on Mindbox.YandexTracker/Extensions/DtoExtension.cs
> +	public static Resolution ToResolution(this FieldInfo value) => value.Id switch
поправил

2024-10-03 10:16 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		while (true)
поправил

2024-10-03 20:30 UTC, Markeli requested changes

2024-10-03 20:30 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +			$"statuses",
Тут и еще в нескольких местах у тебя есть лишний значок интерполяции строки. Можно его убрать.

2024-10-03 20:30 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		using var httpClient = httpClientFactory.CreateClient();
У тебя ниже в `ExecuteAndProcessResultAsync` IDE ругается, что `captured value disposed in the outer scope`.

2024-10-03 20:30 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		async Task<TResult> ExecuteAndProcessResultAsync(CancellationToken cancellationToken)
Ты тут токен отмены скрываешь из внешнего скоупа.

2024-10-03 20:30 UTC, Markeli commented on Mindbox.YandexTracker/Extensions/OtherExtensions.cs
> +internal static class OtherExtensions
Какое-то сомнительное название для класса. Но лучше предложить ничего не могу)

2024-10-04 08:40 UTC, toporoviv commented on Mindbox.YandexTracker/Extensions/OtherExtensions.cs
> +internal static class OtherExtensions
тогда разобью его на 2 класса, чтобы было понятней

2024-10-04 08:57 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		using var httpClient = httpClientFactory.CreateClient();
в лс договорились, что создадим httpClient в конструкторе один раз и будем использовать его в других методах

2024-10-04 09:02 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +			$"statuses",
поправил

2024-10-04 09:02 UTC, toporoviv commented on Mindbox.YandexTracker/Extensions/DtoExtension.cs
> +		ArgumentNullException.ThrowIfNull(issueStatusInfo);
поправил

2024-10-04 09:02 UTC, toporoviv commented on Mindbox.YandexTracker/Extensions/DtoExtension.cs
> +		IReadOnlyList<GetIssueStatusResponse> issueStatusInfos)
поправил

2024-10-04 09:03 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		async Task<TResult> ExecuteAndProcessResultAsync(CancellationToken cancellationToken)
поправил

2024-10-04 09:13 UTC, toporoviv commented on Mindbox.YandexTracker/Extensions/OtherExtensions.cs
> +internal static class OtherExtensions
поправил

2024-10-07 13:55 UTC, Markeli requested changes

2024-10-07 13:55 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		_httpClient = httpClientFactory.CreateClient();
Надо задиспоузить.

2024-10-07 13:55 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		ArgumentNullException.ThrowIfNull(queueKey);
Это строка. Сюда по ошибке могут передать пустую строку или пробелы. Лучше проверять через `ArgumentNullException.ThrowIfNullOrWhiteSpace`. Если нам передадут в качестве аргументов какую-то дичь, мы точно об этом узнаем.

Поправь, плиз, везде тут проверки.

2024-10-07 13:55 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +				: ((QueueExpandData)expand).ToQueryString();
Сходу не обратил внимания. Зачем тут лишний каст к типу? Можно же вот так написать:

```
expand.Value.ToQueryString()

``` 

2024-10-07 13:55 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +			payload: file,
Есть опасения на счет этого метода. Обычно же здесь передается некий объект, который потом сериализуется в json. Точно ли метод создания аттача работает так? Разве тут не надо как-то иначе отправлять содержимое файла?

2024-10-07 13:55 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		if (request.FieldsWhichIncludedInResponse is not null
Давай назовем поле `ReturnedFields`. Так более лаконично.

P.S. Это поле есть в нескольких классах.

2024-10-07 13:55 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		_httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("OAuth", optionsSnapshot.Token);
А почему это тут осталось? Мы же клиента создаем один раз, инициализируем его в конструкторе. Логично это тоже вынести туда.

2024-10-07 13:55 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		while (dataChunk.Count < perPage && withPagination);
Какой-то очень странный костыль. Зачем тут какой-то флаг? Он всегда  false, потому что ты его не выставляешь.

Нормальное условие выхода же простое:

```c#
while (dataChunk.Count == perPage)
```

2024-10-07 14:13 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		_httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("OAuth", optionsSnapshot.Token);
Поправил.

2024-10-07 14:28 UTC, toporoviv commented on Mindbox.YandexTracker.Abstractions/Interfaces/IYandexTrackerClient.cs
> +	public Task<IReadOnlyList<GetIssueTypeResponse>> GetIssueTypesAsync(
поправил

2024-10-07 14:31 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		ArgumentNullException.ThrowIfNull(queueKey);
поправил

2024-10-07 14:36 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +				: ((QueueExpandData)expand).ToQueryString();
поправил

2024-10-07 14:37 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		if (request.FieldsWhichIncludedInResponse is not null
поправил

2024-10-07 14:39 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		_httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("OAuth", optionsSnapshot.Token);
тут меня опередили, уже исправлено

2024-10-07 14:39 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		while (dataChunk.Count < perPage && withPagination);
поправил

2024-10-07 15:04 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		_httpClient = httpClientFactory.CreateClient();
поправил

2024-10-07 18:46 UTC, Markeli commented on Mindbox.YandexTracker.Abstractions/Interfaces/IYandexTrackerClient.cs
> +	public Task<IReadOnlyList<GetIssueTypeResponse>> GetIssueTypesAsync(
Не залито(

2024-10-08 09:32 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +			payload: file,
Пока еще не то, что надо.

В методе `CreateAttachmentAsync` ты правильно формируешь тело запроса для отправки. Но дальше ты его передаешь в `payload`, и внутри `ExecuteYandexTrackerApiRequestAsync` оно будет сконвертировано в json.

Вот тут надо добавить проверку, а что тебе передали. Если это какой-то наследник HttpContent, то надо в `request.Content` ставить его as-is. Если нет, то конвертить в json.

2024-10-08 10:13 UTC, Markeli approved these changes

2024-10-08 10:14 UTC, merged