Added integration tests
mindbox-cloud/Mindbox.YandexTracker pull request #5
Opened 2024-10-08 21:05 UTC by toporoviv

[Написать библиотеку для работы с Яндекс.Трекером](https://tracker.yandex.ru/GITLAB-5)

2024-10-09 13:16 UTC, Markeli requested changes

2024-10-09 13:16 UTC, Markeli commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		var attachments = (await YandexTrackerClient.GetAttachmentsAsync(issue.Key)).ToArray();
Я в личке отписывался, что это тест падает. У тебя с ним все ок?

У меня при локальном запуске была ошибка, что аттач нельзя получить, потому он временный. Он станет постоянным, когда мы создадим коммент с аттачем или к задаче приаттачим файл.

2024-10-09 13:16 UTC, Markeli commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		var userId = "8000000000000001";
У нас в конфиге задается юзер, лучше его использовать. Там же в конфиге можно имя задать для сравнения в Assert.

2024-10-09 13:41 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		var projectType = entityType.ToLowerInvariant();
да

2024-10-09 13:43 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +			$"entities/{projectType}",
поправил

2024-10-09 13:46 UTC, toporoviv commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		await Task.Delay(1000);
Некоторые подобные тесты не проходили. Например, после создания двух задач я запрашивал их, возвращалась одна. Я подумал, что сервер просто не успевает их создать/зарегистрировать у себя пока я их запрашиваю. Добавил задержку - все заработало

2024-10-09 13:56 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		httpClient.DefaultRequestHeaders.Host = "api.tracker.yandex.net";
в апишке было написано про хедер Host с таким значением, но и без него все работает

2024-10-09 13:56 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		httpClient.DefaultRequestHeaders.Host = "api.tracker.yandex.net";
поправил

2024-10-09 14:01 UTC, toporoviv commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		var userId = "8000000000000001";
поправил

2024-10-09 14:24 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +			localQueueFields = (await ExecuteYandexTrackerCollectionRequestAsync<GetIssueFieldsResponse>(
поправил

2024-10-09 14:41 UTC, toporoviv commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +	public async Task GetQuqueAsync_ValidQueueKey_AllFieldsIncludedInResponse_ShouldReturnExistingQuque()
поправил

2024-10-09 14:42 UTC, toporoviv commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +	public async Task GetIssueAsync_IssueKey_ResponseIsNotNull()
поправил

2024-10-09 14:43 UTC, toporoviv commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		var someIssueKey = "randomIssue";
поправил

2024-10-09 19:36 UTC, toporoviv commented on Mindbox.YandexTracker.Abstractions/Mindbox.YandexTracker.Abstractions.csproj
> +  <ItemGroup>
поправил

2024-10-09 19:38 UTC, toporoviv commented on Mindbox.YandexTracker.Tests/YandexTrackerTestBase.cs
> +			LeadKey = "ya.toporow",
Добавил CurrentUserLogin. В тесте GetUserById будут использоваться CurrentUserId и CurrentUserLogin

2024-10-10 09:07 UTC, Markeli commented on Mindbox.YandexTracker.Tests/YandexTrackerTestBase.cs
> +		await YandexTrackerClient.DeleteQueueAsync(TestQueueKey);
А еще куча досок проектов.
<img width="1995" alt="image" src="https://github.com/user-attachments/assets/069bdc67-f759-4a01-8b8b-d62a485a9faf">

При создании проекта автоматически создается доска для него. Выглядит так, что в тестах после создания проекта надо получить доску для него, затем удалить проекта и вместе с ним доску.

2024-10-10 09:07 UTC, Markeli commented on Mindbox.YandexTracker.Tests/YandexTrackerTestBase.cs
> +		await YandexTrackerClient.DeleteQueueAsync(TestQueueKey);
И существующий мусор в трекере надо удалить.

2024-10-10 13:35 UTC, toporoviv commented on Mindbox.YandexTracker.Tests/YandexTrackerTestBase.cs
> +		await YandexTrackerClient.DeleteQueueAsync(TestQueueKey);
поправил

2024-10-10 18:28 UTC, Markeli requested changes

2024-10-10 18:28 UTC, Markeli commented on Mindbox.YandexTracker.Abstractions/Mindbox.YandexTracker.Abstractions.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
Это сборка абстракции. Не должно быть в Abstractions зависимостей от других сборок. 

P.S. Иногда можно, но это должно быть максимально обосновано. У нас не тот случай.

2024-10-10 18:28 UTC, Markeli commented on Mindbox.YandexTracker/Extensions/StringExtensions.cs
> +	public static string ToLowerInvariant(this ProjectEntityType value)
Давай переименуем этот метод в `ToYandexRouteSegment`.  А то `ToLowerInvariant` как-то глаза слишком режет.

2024-10-10 19:02 UTC, toporoviv commented on Mindbox.YandexTracker/Extensions/StringExtensions.cs
> +	public static string ToLowerInvariant(this ProjectEntityType value)
поправил

2024-10-10 19:04 UTC, toporoviv commented on Mindbox.YandexTracker.Abstractions/Mindbox.YandexTracker.Abstractions.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
поправил

2024-10-10 21:24 UTC, toporoviv commented on Directory.Build.props
> +    <VersionMinor>3</VersionMinor>
поправил

2024-10-10 21:25 UTC, toporoviv commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		var components = await YandexTrackerClient.GetComponentsAsync();
поправил

2024-10-11 06:40 UTC, toporoviv commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		var attachments = (await YandexTrackerClient.GetAttachmentsAsync(issue.Key)).ToArray();
в данном случае не получится сравнивать коллекции Attacment, т.к. при создании (прикреплении) файла нам возвращается респонс без Thumbnail, а при получении файлов появляется этот Thumbnail, поэтому сравнении коллекций всегда будет давать false. Тест подправил, теперь проходит

2024-10-11 10:40 UTC, Markeli commented on Mindbox.YandexTracker/Extensions/StringExtensions.cs
> +	public static string ToLowerInvariant(this ProjectEntityType value)
FYI, вот такой коммент лучше:
<img width="910" alt="image" src="https://github.com/user-attachments/assets/52735322-55e5-423f-8c32-c5511052da31">
Не просто название pragma пишем в коменте, а коротко, что от нас хотят и почему мы навесили вообще pragma.

А то код pragma гуглится быстро. Но важнее же понять, почему мы ее сделали.

2024-10-11 10:54 UTC, Markeli commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		var attachments = (await YandexTrackerClient.GetAttachmentsAsync(issue.Key)).ToArray();
Остался неиспользуемый код. 
<img width="976" alt="image" src="https://github.com/user-attachments/assets/b075829c-6b65-4b1b-b3ae-7a3d252b1a2e">

2024-10-11 10:55 UTC, Markeli commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		var attachments = (await YandexTrackerClient.GetAttachmentsAsync(issue.Key)).ToArray();
Fixed.

2024-10-11 13:20 UTC, Markeli commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		var issues = await YandexTrackerClient.GetIssuesFromQueueAsync(TestQueueKey);
Это ненадежный тест. Мы в других методах тоже создаем задачки. Порядок выполнения тестов не задан.

Поэтому он может падать.

Думаю, достаточно будет переписать Assert, что в очереди не меньше двух задач и там есть созданные нами.

2024-10-11 13:23 UTC, Markeli commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +			Summary = "Testik2"
Summary `Testik2` используется у тебя в других метода при создании задач. Так что упадет тест.

2024-10-11 13:23 UTC, Markeli commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		var issues = await YandexTrackerClient.GetIssuesByQueryAsync(
Тоже самое замечание про "Testik2"

2024-10-11 13:24 UTC, Markeli commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		var component1 = await YandexTrackerClient.CreateComponentAsync("someName", TestQueueKey);
Можно создать два компонентами с одинаковым названием?

2024-10-11 13:25 UTC, Markeli commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		Assert.AreEqual(comment1.Id, comments.First().Id);
Сначала лучше проверить, что получил ожидаемое количество комментов. А то мало ли, количество отличается, упадет не Assert, а тест из-за ошибки в Linq.

2024-10-11 13:26 UTC, Markeli commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		Assert.AreEqual(comment2.Id, comments.Last().Id);
Кстати, там у же комменты могут возвращаться не в хронологическом порядке. Лучше явно отсортировать комменты по дате.

2024-10-11 13:27 UTC, Markeli commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		await Task.Delay(1000);  // Чтобы задачи точно создались в трекере
У тебя Delay есть только в issues. Может, и в остальных местах его добавить, где мы для теста что-то создаем. Чтобы тест не флачил (работал стабильно).

2024-10-11 13:36 UTC, Markeli commented on Mindbox.YandexTracker/Extensions/RequestExtensions.cs
> +				dict.Add(prop.Name.ToLowerInvariant(), value!);
А тут точно поля нужно в lowercase? В доке видел названия полей в camelCase.

2024-10-11 13:38 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		if (description is not null)
Странность какая-то. Это точно должно идти как query параметры, а в не body внутри request?

2024-10-11 13:58 UTC, toporoviv commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		Assert.AreEqual(comment1.Id, comments.First().Id);
поправил

2024-10-11 14:00 UTC, toporoviv commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		await Task.Delay(1000);  // Чтобы задачи точно создались в трекере
поправил

2024-10-11 14:10 UTC, toporoviv commented on Mindbox.YandexTracker/Extensions/RequestExtensions.cs
> +				dict.Add(prop.Name.ToLowerInvariant(), value!);
тест (создание issue через IssuesFilter) падал с сообщением "...нет поля Summary". Я исправил на нижний регистр и все заработало. Добавлю коммент к прагме

2024-10-11 14:12 UTC, toporoviv commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		var component1 = await YandexTrackerClient.CreateComponentAsync("someName", TestQueueKey);
вряд ли, но в тесте проверка так устроена, что хватит и одного, чтобы тест прошел

2024-10-11 14:12 UTC, toporoviv commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		var component1 = await YandexTrackerClient.CreateComponentAsync("someName", TestQueueKey);
поправил

2024-10-11 14:21 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		if (description is not null)
точно, это должно идти в body

2024-10-11 14:23 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClient.cs
> +		if (description is not null)
поправил

2024-10-11 16:13 UTC, toporoviv commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		var issues = await YandexTrackerClient.GetIssuesByQueryAsync(
поправил

2024-10-11 16:14 UTC, toporoviv commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +			Summary = "Testik2"
поправил

2024-10-11 16:14 UTC, toporoviv commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> +		var issues = await YandexTrackerClient.GetIssuesFromQueueAsync(TestQueueKey);
поправил

2024-10-11 16:15 UTC, toporoviv commented on Mindbox.YandexTracker.Tests/YandexTrackerTestBase.cs
> +	[TestInitialize]
в лс договорились создавать одну очередь на все тесты, поэтому атрибут заменяется на ClassInitialize

2024-10-11 16:46 UTC, merged