Added template
mindbox-cloud/Mindbox.YandexTracker pull request #6
Opened 2024-10-09 13:24 UTC by toporoviv

[Написать библиотеку для работы с Яндекс.Трекером](https://tracker.yandex.ru/GITLAB-5)

2024-10-09 14:07 UTC, Markeli requested changes

2024-10-09 14:07 UTC, Markeli commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +		throw new NotImplementedException();
Такого тут быть не должно.

2024-10-09 14:07 UTC, Markeli commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +		cache.TryGetValue(projects, out IReadOnlyList<Project>? cacheProjects);
Чекни все методы с кэшированием, там везде такая проблема.

2024-10-09 14:07 UTC, Markeli commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +		return await yandexTrackerClient.GetResolutionsAsync(cancellationToken);
Тут тоже можно кэширование прикрутить.

2024-10-09 14:07 UTC, Markeli commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +		return await yandexTrackerClient.GetIssueTypesAsync(cancellationToken);
Тут тоже кэширование нужно прикрутить.

2024-10-09 14:07 UTC, Markeli commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +		throw new NotImplementedException();
Тут тоже кэширование нужно прикрутить.

2024-10-09 14:07 UTC, Markeli commented on Mindbox.YandexTracker.Template/Mindbox.YandexTracker.Template.csproj
> +    <TargetFramework>net8.0</TargetFramework>
У нас пакеты должны спокойно ставиться не только в .net 8 приложения. Они быть .netstandard. 

Посмотри на другие сборки в этом же solution'е.

2024-10-09 14:07 UTC, Markeli commented on Mindbox.YandexTracker.Template/Mindbox - Backup.YandexTracker.Template.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Какой-то мусорный файл.

2024-10-09 14:07 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClientOptions.cs
> +	public required string Token { get; set; }
Почему меняем на set?

2024-10-09 14:09 UTC, Markeli requested changes

2024-10-09 14:09 UTC, Markeli commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +public sealed class CachingYandexTrackerClient(
И надо бы unit тест на эту штуку накинуть.

2024-10-10 07:05 UTC, toporoviv commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +public sealed class CachingYandexTrackerClient(
поправил

2024-10-10 07:06 UTC, toporoviv commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +	public void Dispose()
поправил

2024-10-10 07:07 UTC, toporoviv commented on Mindbox.YandexTracker.Template/Mindbox.YandexTracker.Template.csproj
> +    <TargetFramework>net8.0</TargetFramework>
поправил

2024-10-10 08:37 UTC, toporoviv commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +		var accessibleFields = "accessibleFields";
поправил

2024-10-10 08:41 UTC, toporoviv commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +	public async Task<Attachment> CreateAttachmentAsync(
поправил

2024-10-10 08:41 UTC, toporoviv commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +	private readonly MemoryCacheEntryOptions _memoryCacheOptions =
поправил

2024-10-10 08:49 UTC, toporoviv commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +		return await yandexTrackerClient.GetResolutionsAsync(cancellationToken);
добавил

2024-10-10 08:49 UTC, toporoviv commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +		return await yandexTrackerClient.GetIssueTypesAsync(cancellationToken);
добавил

2024-10-10 08:49 UTC, toporoviv commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +		throw new NotImplementedException();
добавил

2024-10-10 08:49 UTC, toporoviv commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +		throw new NotImplementedException();
поправил

2024-10-10 09:09 UTC, toporoviv commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +	public async Task<IReadOnlyList<UserDetailedInfo>> GetUsersAsync(CancellationToken cancellationToken = default)
в лс договорились еще о кэшировании пользователей

2024-10-10 09:23 UTC, toporoviv commented on Mindbox.YandexTracker/YandexTrackerClientOptions.cs
> +	public required string Token { get; set; }
при регистрации ioc мы обращаемся к полям, уже созданного класса, а значит его поля уже инициализированы и мы их изменять не можем, поэтому возникла необходимость поменять init на set

2024-10-10 09:39 UTC, Markeli commented on Mindbox.YandexTracker/YandexTrackerClientOptions.cs
> +	public required string Token { get; set; }
Справедливо.

2024-10-10 14:16 UTC, toporoviv commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +		cache.TryGetValue(projects, out IReadOnlyList<Project>? cacheProjects);
поправил

2024-10-10 14:16 UTC, toporoviv commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +public sealed class CachingYandexTrackerClient(
добавил

2024-10-10 14:18 UTC, toporoviv commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +		var components = "components";
добавил

2024-10-10 14:18 UTC, toporoviv commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +			.SetAbsoluteExpiration(TimeSpan.FromMinutes(10));
поправил

2024-10-10 15:04 UTC, toporoviv commented on Mindbox.YandexTracker.Template/Mindbox - Backup.YandexTracker.Template.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
удалил

2024-10-10 18:34 UTC, Markeli commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +		cache.TryGetValue(projects, out IReadOnlyList<Project>? cacheProjects);
В методе `GetProjectsAsync` у нас куча аргументов.
<img width="985" alt="image" src="https://github.com/user-attachments/assets/81962fd5-f97b-47cf-8812-1e81e0c707d1">

Их все нужно учитывать в ключике кэширования. Иначе будет плохо(

2024-10-10 18:38 UTC, Markeli commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +public sealed class CachingYandexTrackerClient(
TemplateUnitTests - некорректное название для теста. Ты же тестишь YandexTrackerClientCachingDecorator, так и тест так должен называться. А то путаница.

2024-10-10 18:39 UTC, Markeli commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +	public async Task<IReadOnlyList<UserDetailedInfo>> GetUsersAsync(CancellationToken cancellationToken = default)
Список пользователей кэшируем. Надо тогда кэшировать и метод получения данных одного пользователя.

2024-10-10 18:47 UTC, Markeli commented on Mindbox.YandexTracker.Template/YandexTrackerClientCachingDecorator.cs
> +		var cacheKey = $"{options.CacheKeyPrefix}_accessibleFields";
Тут надо учитывать `queueKey` в cacheKey.

2024-10-10 18:47 UTC, Markeli commented on Mindbox.YandexTracker.Template/YandexTrackerClientCachingDecorator.cs
> +		var cacheKey = $"{options.CacheKeyPrefix}_issues_{issuesFilter.GetHashCode()}";
Задачи не надо кэшировать. Детали накинул в ЛС.

2024-10-10 18:49 UTC, Markeli commented on Mindbox.YandexTracker.Template/YandexTrackerClientCachingDecorator.cs
> +		var cacheKey = $"{options.CacheKeyPrefix}_projects_{entityType}_{project.GetHashCode()}";
Тоже обсудили в ЛС. Надо учитывать все параметры в ключе кэширования.

2024-10-10 18:49 UTC, Markeli commented on Mindbox.YandexTracker.Template/YandexTrackerClientCachingDecorator.cs
> +		var cacheKey = $"{options.CacheKeyPrefix}_queues";
expand тоже должен быть в ключе кэширования.

2024-10-11 07:15 UTC, toporoviv commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +public sealed class CachingYandexTrackerClient(
поправил

2024-10-11 07:16 UTC, toporoviv commented on Mindbox.YandexTracker.Template/CachingYandexTrackerClient.cs
> +	public async Task<IReadOnlyList<UserDetailedInfo>> GetUsersAsync(CancellationToken cancellationToken = default)
поправил

2024-10-11 07:17 UTC, toporoviv commented on Mindbox.YandexTracker.Template/YandexTrackerClientCachingDecorator.cs
> +		var cacheKey = $"{options.CacheKeyPrefix}_accessibleFields";
поправил

2024-10-11 07:30 UTC, toporoviv commented on Mindbox.YandexTracker.Template/YandexTrackerClientCachingDecorator.cs
> +		var cacheKey = $"{options.CacheKeyPrefix}_issues_{issuesFilter.GetHashCode()}";
поправил

2024-10-11 07:33 UTC, toporoviv commented on Mindbox.YandexTracker.Template/YandexTrackerClientCachingDecorator.cs
> +		var cacheKey = $"{options.CacheKeyPrefix}_queues";
поправил

2024-10-11 07:39 UTC, toporoviv commented on Mindbox.YandexTracker.Template/YandexTrackerClientCachingDecorator.cs
> +		var cacheKey = $"{options.CacheKeyPrefix}_projects_{entityType}_{project.GetHashCode()}";
поправил

2024-10-11 16:33 UTC, Markeli requested changes

2024-10-11 16:33 UTC, Markeli commented on Mindbox.YandexTracker.Tests/IntegrationsTests/YandexTrackerClientTests.cs
> -public class YandexTrackerClientTests : YandexTrackerTestBase
Вернул.

2024-10-11 16:33 UTC, Markeli commented on Mindbox.YandexTracker.Abstractions/Entities/Issue.cs
> +	public override int GetHashCode()
У issue это можно будет убрать.

2024-10-11 16:40 UTC, Markeli commented on Mindbox.YandexTracker.Abstractions/Entities/Issue.cs
> +	public override int GetHashCode()
Fixed.

2024-10-11 16:41 UTC, merged